/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import classes.Access;
import classes.Annual;
import exception.EmptyInputException;
import exception.QueryException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javafx.scene.control.DatePicker;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AnnualLeave extends javax.swing.JFrame {

    /**
     * Creates new form AnnualLeave
     */
    String userId;
    int accessID;
    boolean adminStatus = false;

    public AnnualLeave() {
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen
    }

    public AnnualLeave(String userId, int accessId, boolean status) {

        this.userId = userId;
        this.accessID = accessId;
        this.adminStatus = status;
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        typeLeave = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReasons = new javax.swing.JTextArea();
        btnApply = new javax.swing.JButton();
        dateFrom = new org.jdesktop.swingx.JXDatePicker();
        dateTo = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAccess = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setText("LOGOUT");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(40, 110, 60, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setText("BACK TO HOME");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 450, 100, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setText("EDIT PROFILE");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(30, 220, 90, 15);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setText("SALARY HISTORY");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 330, 120, 20);

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogout);
        btnLogout.setBounds(30, 30, 80, 80);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/wireframe.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel5.add(btnEdit);
        btnEdit.setBounds(30, 140, 80, 70);

        btnSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalary);
        btnSalary.setBounds(30, 250, 80, 80);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/homepage.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack);
        btnBack.setBounds(30, 380, 80, 70);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("LEAVE FORM");

        btnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel2.setText("Select type of leave:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 113, 17);

        typeLeave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        typeLeave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annual Leave", "Emergency Leave", "Paid Leave", "Unpaid Leave" }));
        jPanel1.add(typeLeave);
        typeLeave.setBounds(190, 40, 180, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel3.setText("From:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 70, 14);

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel4.setText("To:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 60, 17);

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel5.setText("State reasons:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 210, 90, 17);

        txtReasons.setColumns(20);
        txtReasons.setRows(5);
        jScrollPane1.setViewportView(txtReasons);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 200, 166, 96);

        btnApply.setBackground(new java.awt.Color(102, 153, 255));
        btnApply.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnApply);
        btnApply.setBounds(200, 330, 100, 40);
        jPanel1.add(dateFrom);
        dateFrom.setBounds(190, 100, 180, 22);
        jPanel1.add(dateTo);
        dateTo.setBounds(190, 150, 180, 22);

        tblAccess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leave Type", "Leave From", "Leave To", "Reasons", "Approval", "Declined Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccessMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAccess);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(400, 40, 452, 402);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Access().logout(this.accessID);
        new TestLogin().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EditProfile(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffPage(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewSalary(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnSalaryActionPerformed

    private boolean checkInput() throws EmptyInputException {
        String typeLeave = this.typeLeave.getSelectedItem().toString();
        String reasons = this.txtReasons.getText();
        boolean status = false;

        if ((typeLeave != null) && (this.dateFrom.getDate() != null) && (this.dateTo.getDate() != null) && (reasons != null)) {
            status = true;
        } else {
            status = false;
            throw new EmptyInputException();
        }
        return status;
    }

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        try {
            if (this.checkInput()) {
                SimpleDateFormat DateFor = new SimpleDateFormat("dd/MM/yyyy");

                Annual ann = new Annual();
                ann.setAnnualID(ann.getAnnualID());
                ann.setAnnualType(this.typeLeave.getSelectedItem().toString());
                ann.setAnnualDateFrom(DateFor.format(this.dateFrom.getDate()));
                ann.setAnnualDateTo(DateFor.format(this.dateTo.getDate()));
                ann.setAnnualReason(this.txtReasons.getText());
                ann.setEmpId(this.userId);

                if (ann.addAnnual()) {
                    JOptionPane.showMessageDialog(null, "Added Successfully");
                    this.txtReasons.setText("");
                    this.dispose();
                    new AnnualLeave(this.userId,this.accessID,this.adminStatus).setVisible(true);
                }
            }
        } catch (QueryException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (EmptyInputException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnApplyActionPerformed

    private void tblAccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAccessMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        Annual ann = new Annual();

        String[][] arrayStaffAnnual = ann.staffAnnual(this.userId);

        DefaultTableModel model3 = (DefaultTableModel) this.tblAccess.getModel();

        if (arrayStaffAnnual != null) {
            for (int i = 0; i < arrayStaffAnnual.length; i++) //for loop to print the array  
            {
                String approval = null;
                if (arrayStaffAnnual[i][4] == null) {
                    approval = "Pending";
                } else if ("1".equals(arrayStaffAnnual[i][4])) {
                    approval = "Approved";
                } else {
                    approval = "Declined";
                }
                model3.addRow(new Object[]{arrayStaffAnnual[i][0], arrayStaffAnnual[i][1], arrayStaffAnnual[i][2], arrayStaffAnnual[i][3], approval , arrayStaffAnnual[i][5]});
            }
            this.tblAccess.setModel(model3);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnualLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnualLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnualLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnualLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnnualLeave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSalary;
    private org.jdesktop.swingx.JXDatePicker dateFrom;
    private org.jdesktop.swingx.JXDatePicker dateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAccess;
    private javax.swing.JTextArea txtReasons;
    private javax.swing.JComboBox<String> typeLeave;
    // End of variables declaration//GEN-END:variables
}
