/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import classes.Access;
import classes.Employee;
import exception.EmptyInputException;
import exception.QueryException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    String userId;
    int accessID;
    boolean adminStatus;

    public EditProfile() {
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen
    }

    public EditProfile(String userId, int accessId, boolean status) {
        this.userId = userId;
        this.accessID = accessId;
        this.adminStatus = status;
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        btnUpdatePass = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnUpdateProf1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAnnual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSalary1 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnAnnualLeave = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jTextField3.setText("STAFF'S NAME");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jTextField5.setText("STAFF'S GENDER");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jTextField7.setText("XXXX-XX-XXXX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnBack.setText("Back to Home");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditProfileMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 60, 80, 70);

        jLabel9.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel9.setText("New Password:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 190, 110, 17);

        txtPass.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel1.add(txtPass);
        txtPass.setBounds(100, 220, 170, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel10.setText("Re-enter New Password:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 260, 160, 17);

        txtNewPass.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel1.add(txtNewPass);
        txtNewPass.setBounds(100, 280, 170, 30);

        btnUpdatePass.setBackground(new java.awt.Color(0, 102, 255));
        btnUpdatePass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdatePass.setText("Update Password");
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdatePass);
        btnUpdatePass.setBounds(110, 380, 155, 40);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        btnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(65, 65, 65)
                .addComponent(btnClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 370, 40);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel1.setText("Staff ID:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 220, 46, 17);

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel4.add(txtID);
        txtID.setBounds(20, 240, 170, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel2.setText("Staff Name:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 280, 70, 17);

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel3.setText("Gender:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 340, 50, 17);

        jLabel7.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel7.setText("Date of Birth:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 400, 80, 17);

        jLabel6.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel6.setText("Phone Number:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 280, 100, 17);

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel4.add(txtName);
        txtName.setBounds(20, 300, 170, 30);

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        jPanel4.add(txtGender);
        txtGender.setBounds(20, 360, 170, 30);

        txtBirth.setEditable(false);
        txtBirth.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel4.add(txtBirth);
        txtBirth.setBounds(20, 420, 170, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel8.setText("IC Number:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(230, 220, 80, 17);

        txtIC.setEditable(false);
        txtIC.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICActionPerformed(evt);
            }
        });
        jPanel4.add(txtIC);
        txtIC.setBounds(230, 240, 170, 30);

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel4.add(txtPhone);
        txtPhone.setBounds(230, 300, 170, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel5.setText("Email Address:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(230, 340, 90, 17);

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jPanel4.add(txtEmail);
        txtEmail.setBounds(230, 360, 170, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel4.setText("Address:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(230, 400, 60, 17);

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(230, 420, 170, 96);

        btnEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit);
        btnEdit.setBounds(230, 110, 140, 40);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EDIT PROFILE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(150, 150, 150))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 430, 40);

        btnUpdateProf1.setBackground(new java.awt.Color(51, 102, 255));
        btnUpdateProf1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateProf1.setText("Update Profile");
        btnUpdateProf1.setEnabled(false);
        btnUpdateProf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProf1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdateProf1);
        btnUpdateProf1.setBounds(130, 530, 140, 40);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        btnAnnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnualMouseClicked(evt);
            }
        });
        jPanel5.add(btnAnnual);
        btnAnnual.setBounds(30, 270, 70, 0);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setText("LOGOUT");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(40, 110, 60, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setText("BACK TO HOME");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 450, 100, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setText("SALARY HISTORY");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 230, 120, 20);

        btnSalary1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        btnSalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalary1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalary1);
        btnSalary1.setBounds(30, 150, 80, 80);

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/homepage.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack1);
        btnBack1.setBounds(30, 380, 80, 70);

        jLabel14.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel14.setText("ANNUAL LEAVE APPLICATION");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 340, 110, 30);

        btnAnnualLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/calendar.png"))); // NOI18N
        btnAnnualLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnualLeaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnAnnualLeave);
        btnAnnualLeave.setBounds(30, 270, 80, 70);

        btnLogout2.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout2.setBorder(null);
        btnLogout2.setBorderPainted(false);
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogout2);
        btnLogout2.setBounds(30, 30, 80, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private boolean checkInput() throws EmptyInputException {
        boolean status;

        if (!this.txtPass.getText().isEmpty() && !this.txtPass.getText().isEmpty()) {
            status = true;
        } else {
            status = false;
            throw new EmptyInputException();
        }

        return status;
    }
    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
        // TODO add your handling code here:
        try {
            Employee emp = new Employee();

            if (checkInput()) {
                if (this.txtPass.getText().equals(this.txtNewPass.getText())) {
                    System.out.println(this.txtPass.getText() + this.userId + this.adminStatus);
                    if (emp.updatePassword(this.txtPass.getText(), this.userId, this.adminStatus)) {
                        JOptionPane.showMessageDialog(null, "Password has been updated");
                    }else{
                        JOptionPane.showMessageDialog(null, "Password cannot be updated");
                    }
                }
            }
        } catch (EmptyInputException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (QueryException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnUpdatePassActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        StaffPage frm = new StaffPage();
        frm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.txtEmail.setEditable(true);
        this.txtPhone.setEditable(true);
        this.txtName.setEditable(true);
        this.txtAddress.setEditable(true);
        this.btnUpdateProf1.setEnabled(true);

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditProfileMouseClicked
        // TODO add your handling code here:
        this.hide();
        new ViewSalary().setVisible(true);
    }//GEN-LAST:event_btnEditProfileMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnAnnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnualMouseClicked
        // TODO add your handling code here:
        this.hide();
        new AnnualLeave(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnAnnualMouseClicked

    private void btnSalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalary1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewSalary(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnSalary1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffPage(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnUpdateProf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProf1ActionPerformed
        // TODO add your handling code here:
        Employee emp = new Employee();
        emp.setEmp_address(this.txtAddress.getText());
        emp.setEmp_contact(this.txtPhone.getText());
        emp.setEmp_email(this.txtEmail.getText());
        emp.setEmp_dob(Date.valueOf(this.txtBirth.getText()));
        emp.setEmp_name(this.txtName.getText());

        if (emp.updateEmployeeForStaff(this.userId)) {
            JOptionPane.showMessageDialog(null, "Details Updated");
            this.btnUpdateProf1.setEnabled(false);
        }
    }//GEN-LAST:event_btnUpdateProf1ActionPerformed

    private void txtICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Employee emp = new Employee();
        String[] employee = emp.selectEmployee(this.userId);

        this.txtID.setText(this.userId);
        this.txtName.setText(employee[1]);
        this.txtPhone.setText(employee[6]);
        this.txtEmail.setText(employee[3]);
        this.txtIC.setText(employee[4]);
        this.txtBirth.setText(employee[5]);
        this.txtGender.setText(employee[7]);
        this.txtAddress.setText(employee[8]);
    }//GEN-LAST:event_formWindowOpened

    private void btnAnnualLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnualLeaveActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AnnualLeave(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnAnnualLeaveActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnnual;
    private javax.swing.JButton btnAnnualLeave;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel btnEditProfile;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnSalary1;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JButton btnUpdateProf1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
