/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import admin.HomepageAdmin;
import classes.Access;
import classes.Employee;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class StaffPage extends javax.swing.JFrame {

    /**
     * Creates new form StaffPage
     */
    String userId;
    boolean adminStatus = false;
    int accessID;

    public StaffPage() {
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen
    }

//    public StaffPage(String userId, int accessId) {
//        this.userId = userId;
//        this.accessID = accessId;
//        initComponents();
//        this.setLocationRelativeTo(null); //set form to center screen
//    }

    public StaffPage(String userId, int accessId, boolean admin) {
        this.userId = userId;
        this.adminStatus = admin;
        this.accessID = accessId;
        initComponents();
        this.setLocationRelativeTo(null); //set form to center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnnual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnAnnualLeave1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnAnnualLeave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btnAnnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnualMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnnual);
        btnAnnual.setBounds(30, 380, 70, 0);

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setText("LOGOUT");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 110, 60, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setText("ANNUAL LEAVE APPLICATION");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 430, 110, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setText("EDIT PROFILE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 220, 90, 15);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setText("SALARY HISTORY");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 330, 120, 20);

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(30, 30, 80, 80);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/wireframe.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(30, 140, 80, 70);

        btnSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalary);
        btnSalary.setBounds(30, 250, 80, 80);

        jLabel15.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel15.setText("ADMINISTRATOR");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 560, 110, 30);

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Administrator-icon.png"))); // NOI18N
        btnAdmin.setEnabled(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin);
        btnAdmin.setBounds(30, 460, 80, 100);

        btnAnnualLeave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/calendar.png"))); // NOI18N
        btnAnnualLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnualLeave1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnnualLeave1);
        btnAnnualLeave1.setBounds(30, 360, 80, 70);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 260, 55, 17);

        txtEmpID.setEditable(false);
        txtEmpID.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jPanel2.add(txtEmpID);
        txtEmpID.setBounds(70, 290, 180, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(310, 350, 77, 17);

        txtDOB.setEditable(false);
        txtDOB.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtDOB.setText("MM-DD-YY");
        jPanel2.add(txtDOB);
        txtDOB.setBounds(310, 370, 170, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff Name: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 340, 70, 17);

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtName.setText("FULL NAME");
        jPanel2.add(txtName);
        txtName.setBounds(70, 370, 180, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(520, 260, 91, 17);

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtPhone.setText("601X-XXXXXX");
        jPanel2.add(txtPhone);
        txtPhone.setBounds(520, 290, 180, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(310, 260, 46, 17);

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtGender.setText("GENDER");
        jPanel2.add(txtGender);
        txtGender.setBounds(310, 290, 170, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email address:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(310, 420, 81, 17);

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtEmail.setText("XXXX@XXXX.COM");
        jPanel2.add(txtEmail);
        txtEmail.setBounds(310, 450, 170, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IC Number :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 420, 67, 17);

        txtIC.setEditable(false);
        txtIC.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txtIC.setText("XXXX-XX-XXXX");
        jPanel2.add(txtIC);
        txtIC.setBounds(70, 450, 180, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(520, 350, 48, 17);

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(520, 380, 190, 96);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USER PROFILE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel14)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 39, 760, 44);

        btnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel2.add(btnClose);
        btnClose.setBounds(738, 6, 12, 22);

        btnAnnualLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Administrator-icon.png"))); // NOI18N
        btnAnnualLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnualLeaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnnualLeave);
        btnAnnualLeave.setBounds(330, 100, 140, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnAnnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnualMouseClicked
        // TODO add your handling code here:
        this.hide();
        new AnnualLeave(this.userId, this.accessID,this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnAnnualMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Access().logout(this.accessID);
        new TestLogin().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EditProfile(this.userId, this.accessID, this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewSalary(this.userId, this.accessID , this.adminStatus ).setVisible(true);
    }//GEN-LAST:event_btnSalaryActionPerformed

    private void btnAnnualLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnualLeaveActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AnnualLeave(this.userId, this.accessID ,  this.adminStatus).setVisible(true);
    }//GEN-LAST:event_btnAnnualLeaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (this.adminStatus) {
            this.btnAdmin.setEnabled(true);
        }

        Employee emp = new Employee();
        String[] empArray = emp.selectEmployee(this.userId);
        emp.selectEmployee(this.userId);
        this.txtAddress.setText(empArray[8]);
        this.txtDOB.setText(empArray[5]);
        this.txtEmail.setText(empArray[3]);
        this.txtEmpID.setText(empArray[0]);
        this.txtGender.setText(empArray[7]);
        this.txtIC.setText(empArray[4]);
        this.txtName.setText(empArray[1]);
        this.txtPhone.setText(empArray[6]);
    }//GEN-LAST:event_formWindowOpened

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnAnnualLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnualLeave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnnualLeave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JLabel btnAnnual;
    private javax.swing.JButton btnAnnualLeave;
    private javax.swing.JButton btnAnnualLeave1;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
